add AD test to pre-commit script remove unnecessary function

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -15,6 +15,14 @@ then
 fi
 echo OK
 
+echo -n "Running AD Test . . . "
+if ! ./libad-test-dbg 20 1 1e-18
+then
+    echo "AD Test failed!"
+    exit 1
+fi
+echo OK
+
 #echo -n "Running Dual Test . . . "
 #./dual-test 6 _ 4 -3 >/tmp/dual-test.txt
 #if ! diff --context=1 /tmp/dual-test.txt dual-test.txt
