a little more testing . . .

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -32,11 +32,29 @@ then
 fi
 echo OK
 
-echo -n "Running AD Library Test . . . "
+echo -n "Running AD Library Test (x = 3.0) . . . "
 export LD_LIBRARY_PATH='.'
-if ! ./libad-test 64 50 2 1e-32 >/dev/null
+if ! ./libad-test 64 50 3 1e-32 >/dev/null
 then
-    echo "AD Library Test failed!"
+    echo "AD Library Test (x = 3.0) failed!"
+    exit 1
+fi
+echo OK
+
+echo -n "Running AD Library Test (x = 0.0) . . . "
+export LD_LIBRARY_PATH='.'
+if ! ./libad-test 64 50 0 1e-32 >/dev/null
+then
+    echo "AD Library Test (x = 0.0) failed!"
+    exit 1
+fi
+echo OK
+
+echo -n "Running AD Library Test (x = -2.0) . . . "
+export LD_LIBRARY_PATH='.'
+if ! ./libad-test 64 50 -2 1e-32 >/dev/null
+then
+    echo "AD Library Test (x = -2.0) failed!"
     exit 1
 fi
 echo OK
