add Dual test to pre-commit build before testing

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -15,10 +15,26 @@ then
 fi
 echo OK
 
-echo -n "Running AD Test . . . "
+echo -n "Running Clang build . . . "
+if ! ./build clang >/dev/null
+then
+    echo "c build failed!"
+    exit 1
+fi
+echo OK
+
+echo -n "Running Dual Test . . . "
+if ! ./libdual-test-dbg 1 1e-18
+then
+    echo "Dual Test failed!"
+    exit 1
+fi
+echo OK
+
+echo -n "Running Taylor Test . . . "
 if ! ./libad-test-dbg 20 1 1e-18
 then
-    echo "AD Test failed!"
+    echo "Taylor Test failed!"
     exit 1
 fi
 echo OK
@@ -40,14 +56,6 @@ echo OK
 #    exit 1
 #fi
 #echo OK
-
-echo -n "Running Clang build . . . "
-if ! ./build clang >/dev/null
-then
-    echo "c build failed!"
-    exit 1
-fi
-echo OK
 
 echo -n "Running Lorenz executables . . . "
 if ! ./tsm-lorenz-dbg 9 16 .01 10000 -15.8 -17.48 35.64 10 28 8 3 >/dev/null 2>&1
