fix assert for x <= 0 check a selection of x values

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -13,19 +13,25 @@ echo -n "Running Clang build . . . "
 ./build clang >/dev/null
 
 echo -n "Running Dual Test . . . "
-if ! ./libdual-test-dbg 1 1e-18
-then
-    echo "Dual Test failed!"
-    exit 1
-fi
+for x in 1 0 -1
+do
+    if ! ./libdual-test-dbg $x 1e-18 0
+    then
+        echo "Dual Test failed!"
+        exit 1
+    fi
+done
 echo OK
 
 echo -n "Running Taylor Test . . . "
-if ! ./libad-test-dbg 20 1 1e-18
-then
-    echo "Taylor Test failed!"
-    exit 1
-fi
+for x in 1 0 -1
+do
+    if ! ./libad-test-dbg 20 $x 1e-18 0
+    then
+        echo "Taylor Test failed!"
+        exit 1
+    fi
+done
 echo OK
 
 echo -n "Running Lorenz executables . . . "
