remove manual inspection tests and data

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,25 +1,13 @@
 #!/bin/sh
-#
-# An example hook script to verify what is about to be committed.
-# Called by "git commit" with no arguments.  The hook should
-# exit with non-zero status after issuing an appropriate message if
-# it wants to stop the commit.
-#
-# To enable this hook, rename this file to "pre-commit".
 
 echo -n "Running Clang build . . . "
-if ! ./build clang >/dev/null
-then
-    echo "c build failed!"
-    exit 1
-fi
-echo OK
+./clean
+./build clang >/dev/null
 
-echo -n "Running AD Test . . . "
-./ad-test-dbg 6 2 1 >/tmp/ad-test.txt
-if ! diff --context=1 /tmp/ad-test.txt ad-test.txt
+echo -n "Running Taylor Test . . . "
+if ! ./libad-test-dbg 32 20 1 1e-18
 then
-    echo "AD Test failed!"
+    echo "Taylor Test failed!"
     exit 1
 fi
 echo OK
